name: liquid_material
description: Liquid Material Components
dependencies:
  browser: any
  liquid: any
  sass: any
dependency_overrides:
  liquid:
    path: ../liquid
  vdom:
    path: ../vdom
transformers:
- sass