name: liquid_material
description: Liquid Material Components
dependencies:
  browser: any
  liquid:
    git: git://github.com/localvoid/liquid.git
  route: any
  vcss: any
dev_dependencies:
  glob: any
  xml: any
dependency_overrides:
  liquid:
    path: ../liquid
  vdom:
    path: ../vdom
  vcss:
    path: ../vcss
  dom_scheduler:
    path: ../dom_scheduler
transformers:
- liquid
