name: liquid_material
description: Liquid Material Components
dependencies:
  browser: any
  liquid:
    git: git://github.com/localvoid/liquid.git
  sass: any
  route: any
dependency_overrides:
  liquid:
    path: ../liquid
  vdom:
    path: ../vdom
transformers:
- sass
- liquid